stages:
    - release

variables:
    IMAGE_TAG: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/rtl-sdr:1.0
   
build-docker-image:
    only:
        changes:
            - Dockerfile
    stage: release
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker info
    script:
        - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
        - docker build -f Dockerfile -t $IMAGE_TAG .
        - docker push $IMAGE_TAG
