version: '3'

services:
  rtl-sdr:
    image: registry.gitlab.com/hassiweb-programming/docker-rtl-sdr/rtl-sdr:1.0
    build: .
    ports:
      - 1234:1234
    devices: 
      - "/dev/bus/usb:/dev/bus/usb"
    
